In [2]:
import numpy as np
import pandas as pd

## Creating NumPy Arrays:
* Create a 1D NumPy array with 10 elements, containing the numbers from 1 to 10.
* Create a 2D NumPy array of shape (3, 4) filled with ones.
* Create a 3x3 identity matrix using NumPy.

In [ ]:
a1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a1Dcf = np.arange(1,11) #cf = using creation function

In [8]:
print(a1D)
print(a1Dcf)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
a2D = np.array([[1, 1, 1, 1], [1,1,1,1], [1,1,1,1]])
a2Dcf = np.ones((3,4), dtype=int)

In [44]:
print(a2D)
print(a2Dcf)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
identityMatrix = np.array([[1,0,0],[0,1,0],[0,0,1]])
iMCf = np.eye(3, dtype=int)
iMCfD = np.diag([1,1,1]) 
print(identityMatrix)
print(iMCf)
print(iMCfD)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Array Operations:
* Add 5 to each element in a 1D NumPy array: [1, 2, 3, 4, 5].
* Multiply each element in a 1D NumPy array: [2, 4, 6, 8, 10] by 2.
* Subtract 3 from each element in a NumPy array: [6, 8, 10, 12, 14].

In [16]:
arr1 = np.arange(1,6)
result = np.add(arr1, 5)
print(arr1)
print("Rsult when 5 is added : ")
print(result)

[1 2 3 4 5]
Rsult when 5 is added : 
[ 6  7  8  9 10]


In [20]:
arr2 = np.arange(2,12,2)
print(arr2)
result2 = np.multiply(arr2, 2)
print("Result when multiplied by 2")
print(result2)

[ 2  4  6  8 10]
Result when multiplied by 2
[ 4  8 12 16 20]


In [22]:
arr3 = np.arange(6,16,2)
print(arr3)
result2 = np.subtract(arr3, 3)
print("Result when subtracted by 3")
print(result2)

[ 6  8 10 12 14]
Result when subtracted by 3
[ 3  5  7  9 11]


### Indexing and Slicing:
- Given a 1D array arr = np.array([10, 20, 30, 40, 50]), access the third 
element.
- Slice a 1D array to get the first 3 elements.
- Given a 2D array, extract the element from the second row and third column.

In [36]:
npArr = np.arange(10, 60, 10)
print(npArr)
print(f"The third elemet is {npArr[2]}")
print(f"The first theree elements are {npArr[:3]}")
np2Arr = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])
print(np2Arr)
print(f"The element from 2nd row and 3rd column is {np2Arr[1, 2]}")

[10 20 30 40 50]
The third elemet is 30
The first theree elements are [10 20 30]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
The element from 2nd row and 3rd column is 23


# Array Statistics:
- Find the minimum and maximum value in a NumPy array: arr = np.array([2, 4, 6,
8, 10]).
- Calculate the sum and mean of the array: arr = np.array([3, 5, 7, 9]).

In [47]:
sArr = np.array([2, 4, 6,8, 10])
print(f"The maximum value of this array is {np.max(sArr)}")
print(f"The minimum value is {np.min(sArr)}")
print(f"The sum of this array is {np.sum(sArr)}")
print(f"The mean of this array is {np.mean(sArr)}")

The maximum value of this array is 10
The minimum value is 2
The sum of this array is 30
The mean of this array is 6.0


## Reshaping and Flattening:
- Reshape a 1D array arr = np.array([1, 2, 3, 4, 5, 6]) into a 2D array of shape
(2, 3).
- Flatten a 2D array arr = np.array([[1, 2, 3], [4, 5, 6]]) into a 1D array.

In [52]:
reArr = np.array([1, 2, 3, 4, 5, 6])
newReArr = reArr.reshape(2,3)
print(reArr)
print(f"The new reshaped 2D array is {newReArr}")
unRearr = np.array([[1, 2, 3], [4, 5, 6]])
flatArr = unRearr.flatten()
print(unRearr)
print(f"The flattern array is {flatArr}")


[1 2 3 4 5 6]
The new reshaped 2D array is [[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
The flattern array is [1 2 3 4 5 6]


### Array Stacking:
 - Stack two 1D arrays [1, 2, 3] and [4, 5, 6] vertically and horizontally.

In [55]:
oneArr = [1,2,3]
twoArr = [4,5,6]
horArr = np.hstack((oneArr, twoArr))
verArr = np.vstack((oneArr, twoArr))
print(f"Horizontal Stakc is {horArr}")
print(f"Verical Stack is {verArr}")

Horizontal Stakc is [1 2 3 4 5 6]
Verical Stack is [[1 2 3]
 [4 5 6]]


## Mathematical Operations:
- Perform element-wise addition and subtraction on two arrays: arr1 = np.array([2, 4,
6]) and arr2 = np.array([1, 3, 5]).
- Perform element-wise multiplication and division on two arrays: arr1 = np.array([2, 
4, 6]) and arr2 = np.array([1, 2, 3]).

In [ ]:
arr1 = np.array([2,4,6])
arr2 = np.array([1,3,5])
addResult = np.add(arr1, arr2)
print(f"The result of addition is {addResult}")
print(f"The result of division is {np.divide(arr1, arr2)}")
print(f"The result of multiplication is {np.multiply(arr1, arr2)}")

The result of addition is [ 3  7 11]
The result of division is [2.         1.33333333 1.2       ]
The result of multiplication is [ 2 12 30]


## Linear Algebra:
- Calculate the dot product of two 1D arrays: arr1 = np.array([1, 2]) and arr2 = 
np.array([3, 4]).
- Multiply two matrices using np.dot(). Given matrices A = np.array([[1, 2], [3,
4]]) and B = np.array([[5, 6], [7, 8]]), compute their dot product.


In [58]:
arr4 = np.array([1, 2]) 
arr5 = np.array([3, 4])
print(f"The dot product of two array is : {np.dot(arr1, arr2)}")

The dot product of two array is : 44


## Random Numbers:
- Generate an array of 10 random numbers between 0 and 1 using np.random.rand().
- Create a random integer array with values between 1 and 100, and of size 5 using 
np.random.randint().

In [74]:
randArray = np.random.rand(10)
print(randArray)
randIntArray = np.random.randint(1, 100, 5)
print(randIntArray)

[0.95877457 0.35574238 0.13711757 0.26205891 0.30685817 0.91978575
 0.98885152 0.41883784 0.30949676 0.42426924]
[15 70 50 26 13]


## Array Comparisons:
- Compare two arrays element-wise: arr1 = np.array([1, 2, 3]) and arr2 = 
np.array([3, 2, 1]). Find which elements in arr1 are greater than arr2.

In [92]:
arr1 = np.array([1, 6, 3])
arr2 = np.array([3, 2, 1])
results = arr1 > arr2
print(results)
print(arr1[results])

[False  True  True]
[6 3]


## Aggregating Functions:
- Use np.sum(), np.mean(), and np.std() to compute the sum, mean, and standard 
deviation of the array arr = np.array([10, 20, 30, 40, 50]).
- Find the index of the maximum value in a NumPy array arr = np.array([5, 2, 8, 
1, 6]) using np.argmax().

In [96]:
arr11= np.array([10, 20, 30, 40, 50])
print(f"The mean of given {arr11} is {np.mean(arr11)}")
print(f"The sum of given {arr11} is {np.sum(arr11)}")
print(f"The standard deviation of given {arr11} is {np.std(arr11)}")

The mean of given [10 20 30 40 50] is 30.0
The sum of given [10 20 30 40 50] is 150
The standard deviation of given [10 20 30 40 50] is 14.142135623730951


## Broadcasting:
 - Add a 1D array [1, 2, 3] to a 2D array [[10, 20, 30], [40, 50, 60]] using 
broadcasting.

In [99]:
d1 = np.array([1,3,3])
d2 = np.array([[10, 20, 30], [40, 50, 60]])
print(d1 + d2)

[[11 23 33]
 [41 53 63]]


## Basic Data Exploration:
- Use .info() to find out what type of data each column contains.
- Use .head() to show the first 5 rows of the dataset.
- Use .describe() to get a summary of numerical columns in the dataset.

In [152]:
df = pd.read_csv('/Users/hoatran/sem3AI/sem4DataMinig/Lab1/data/tasks.csv')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Product_ID      500 non-null    int64 
 1   Product_Name    500 non-null    object
 2   Category        500 non-null    object
 3   Price           500 non-null    int64 
 4   Stock_Quantity  500 non-null    int64 
 5   Rating          500 non-null    int64 
 6   Date_Added      500 non-null    object
dtypes: int64(4), object(3)
memory usage: 27.5+ KB


In [153]:
df.head()

Product_ID Product_Name     Category  Price  Stock_Quantity  Rating  \
0           1   Smartwatch   Stationery   1200              67       1   
1           2   Headphones   Stationery   2000              92       3   
2           3       Laptop   Stationery   1200              89       3   
3           4   Headphones   Stationery    500              48       5   
4           5       Laptop  Electronics   1200              98       4   

   Date_Added  
0  2022-01-01  
1  2022-01-02  
2  2022-01-03  
3  2022-01-04  
4  2022-01-05

In [154]:
df.describe()

Product_ID        Price  Stock_Quantity      Rating
count  500.000000   500.000000      500.000000  500.000000
mean   250.500000  1241.400000       49.252000    3.006000
std    144.481833   709.558303       28.447478    1.477271
min      1.000000   300.000000        1.000000    1.000000
25%    125.750000   700.000000       25.750000    2.000000
50%    250.500000  1200.000000       47.000000    3.000000
75%    375.250000  2000.000000       75.000000    4.000000
max    500.000000  2500.000000       99.000000    5.000000

## Handling Missing Data:
- Fill any missing values in the Price column with the mean price of all products.
- Fill any missing values in the Stock_Quantity column with the median stock quantity.
- Drop any rows that have missing values in the Product_Name column.

In [155]:
print(df.isna().sum())

Product_ID        0
Product_Name      0
Category          0
Price             0
Stock_Quantity    0
Rating            0
Date_Added        0
dtype: int64


## Data Sorting:
- Sort the dataset by the Price column in descending order.
- Sort the dataset by the Stock_Quantity column in ascending order.

In [156]:
df['Price'].sort_values(ascending=False)

332    2500
50     2500
280    2500
58     2500
57     2500
       ... 
413     300
411     300
308     300
191     300
225     300
Name: Price, Length: 500, dtype: int64

In [157]:
df['Stock_Quantity'].sort_values(ascending=True)

196     1
87      1
486     1
143     1
237     1
       ..
214    99
58     99
20     99
203    99
355    99
Name: Stock_Quantity, Length: 500, dtype: int64

## Filtering Data:
- Filter and display all products that have a Price greater than 1000.
- Filter and display all products with a Rating of 4 or higher.


In [165]:
filterePriceAndRating = df[(df['Price'] > 1000) & (df['Rating'] >= 4)] 
print(filterePriceAndRating.sample(n=5, random_state=42))

     Product_ID Product_Name     Category  Price  Stock_Quantity  Rating  \
339         340       Laptop    Furniture   2500              35       4   
50           51     Keyboard  Accessories   2500              50       5   
17           18       Camera  Accessories   1200              63       4   
392         393      Monitor   Stationery   2000              61       4   
293         294       Laptop  Accessories   1200              75       4   

     Date_Added  
339  2022-12-06  
50   2022-02-20  
17   2022-01-18  
392  2023-01-28  
293  2022-10-21  


##  Adding New Columns:
- Add   a   new   column   called  Total_Value  that   represents   the   product   of  Price  and
Stock_Quantity.
- Add a new column Discounted_Price, where products with a Rating of 4 or higher get a
10% discount, and others get a 5% discount.

In [168]:
df['Total_Value'] = df['Price'] * df['Stock_Quantity']
df.head()

Product_ID Product_Name     Category  Price  Stock_Quantity  Rating  \
0           1   Smartwatch   Stationery   1200              67       1   
1           2   Headphones   Stationery   2000              92       3   
2           3       Laptop   Stationery   1200              89       3   
3           4   Headphones   Stationery    500              48       5   
4           5       Laptop  Electronics   1200              98       4   

   Date_Added  Total_Value  
0  2022-01-01        80400  
1  2022-01-02       184000  
2  2022-01-03       106800  
3  2022-01-04        24000  
4  2022-01-05       117600

In [171]:
df['Discounted_Price'] = np.where(df['Rating'] >= 4.0, df['Price'] * 0.90, df['Price'] * 0.95)

In [172]:
df.head()

Product_ID Product_Name     Category  Price  Stock_Quantity  Rating  \
0           1   Smartwatch   Stationery   1200              67       1   
1           2   Headphones   Stationery   2000              92       3   
2           3       Laptop   Stationery   1200              89       3   
3           4   Headphones   Stationery    500              48       5   
4           5       Laptop  Electronics   1200              98       4   

   Date_Added  Total_Value  Discounted_Price  
0  2022-01-01        80400            1140.0  
1  2022-01-02       184000            1900.0  
2  2022-01-03       106800            1140.0  
3  2022-01-04        24000             450.0  
4  2022-01-05       117600            1080.0

## Sorting by Multiple Columns:
- Sort the products first by Category in ascending order, and then by Price in descending
order.

In [178]:
df_sorted = df.sort_values(by=['Category', 'Price'], ascending=[True, False])
df_sorted.head()

Product_ID Product_Name     Category  Price  Stock_Quantity  Rating  \
31          32   Smartphone  Accessories   2500              39       4   
50          51     Keyboard  Accessories   2500              50       5   
58          59       Camera  Accessories   2500              99       4   
89          90       Laptop  Accessories   2500              66       2   
90          91      Monitor  Accessories   2500              88       3   

    Date_Added  Total_Value  Discounted_Price  
31  2022-02-01        97500            2250.0  
50  2022-02-20       125000            2250.0  
58  2022-02-28       247500            2250.0  
89  2022-03-31       165000            2375.0  
90  2022-04-01       220000            2375.0

## Working with Categorical Data:
- Count   how   many   products   are   in   each   category   by   using  .value_counts()  on   the
Category column.

In [179]:
df['Category'].value_counts()

Category
Stationery     139
Electronics    139
Accessories    124
Furniture       98
Name: count, dtype: int64

## Creating a New DataFrame:
- Create a new DataFrame containing only the  Product_ID  and  Price  columns from the
original dataset.

In [186]:
new_df = df[['Product_ID', 'Price']]

In [187]:
new_df.head()

Product_ID  Price
0           1   1200
1           2   2000
2           3   1200
3           4    500
4           5   1200