In [2]:
import numpy as np
import pandas as pd

## Creating NumPy Arrays:
* Create a 1D NumPy array with 10 elements, containing the numbers from 1 to 10.
* Create a 2D NumPy array of shape (3, 4) filled with ones.
* Create a 3x3 identity matrix using NumPy.

In [ ]:
a1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a1Dcf = np.arange(1,11) #cf = using creation function

In [8]:
print(a1D)
print(a1Dcf)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
a2D = np.array([[1, 1, 1, 1], [1,1,1,1], [1,1,1,1]])
a2Dcf = np.ones((3,4), dtype=int)

In [44]:
print(a2D)
print(a2Dcf)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
identityMatrix = np.array([[1,0,0],[0,1,0],[0,0,1]])
iMCf = np.eye(3, dtype=int)
iMCfD = np.diag([1,1,1]) 
print(identityMatrix)
print(iMCf)
print(iMCfD)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Array Operations:
* Add 5 to each element in a 1D NumPy array: [1, 2, 3, 4, 5].
* Multiply each element in a 1D NumPy array: [2, 4, 6, 8, 10] by 2.
* Subtract 3 from each element in a NumPy array: [6, 8, 10, 12, 14].

In [16]:
arr1 = np.arange(1,6)
result = np.add(arr1, 5)
print(arr1)
print("Rsult when 5 is added : ")
print(result)

[1 2 3 4 5]
Rsult when 5 is added : 
[ 6  7  8  9 10]


In [20]:
arr2 = np.arange(2,12,2)
print(arr2)
result2 = np.multiply(arr2, 2)
print("Result when multiplied by 2")
print(result2)

[ 2  4  6  8 10]
Result when multiplied by 2
[ 4  8 12 16 20]


In [22]:
arr3 = np.arange(6,16,2)
print(arr3)
result2 = np.subtract(arr3, 3)
print("Result when subtracted by 3")
print(result2)

[ 6  8 10 12 14]
Result when subtracted by 3
[ 3  5  7  9 11]


### Indexing and Slicing:
- Given a 1D array arr = np.array([10, 20, 30, 40, 50]), access the third 
element.
- Slice a 1D array to get the first 3 elements.
- Given a 2D array, extract the element from the second row and third column.

In [36]:
npArr = np.arange(10, 60, 10)
print(npArr)
print(f"The third elemet is {npArr[2]}")
print(f"The first theree elements are {npArr[:3]}")
np2Arr = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])
print(np2Arr)
print(f"The element from 2nd row and 3rd column is {np2Arr[1, 2]}")

[10 20 30 40 50]
The third elemet is 30
The first theree elements are [10 20 30]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
The element from 2nd row and 3rd column is 23


# Array Statistics:
- Find the minimum and maximum value in a NumPy array: arr = np.array([2, 4, 6,
8, 10]).
- Calculate the sum and mean of the array: arr = np.array([3, 5, 7, 9]).

In [47]:
sArr = np.array([2, 4, 6,8, 10])
print(f"The maximum value of this array is {np.max(sArr)}")
print(f"The minimum value is {np.min(sArr)}")
print(f"The sum of this array is {np.sum(sArr)}")
print(f"The mean of this array is {np.mean(sArr)}")

The maximum value of this array is 10
The minimum value is 2
The sum of this array is 30
The mean of this array is 6.0


## Reshaping and Flattening:
- Reshape a 1D array arr = np.array([1, 2, 3, 4, 5, 6]) into a 2D array of shape
(2, 3).
- Flatten a 2D array arr = np.array([[1, 2, 3], [4, 5, 6]]) into a 1D array.

In [52]:
reArr = np.array([1, 2, 3, 4, 5, 6])
newReArr = reArr.reshape(2,3)
print(reArr)
print(f"The new reshaped 2D array is {newReArr}")
unRearr = np.array([[1, 2, 3], [4, 5, 6]])
flatArr = unRearr.flatten()
print(unRearr)
print(f"The flattern array is {flatArr}")


[1 2 3 4 5 6]
The new reshaped 2D array is [[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
The flattern array is [1 2 3 4 5 6]


### Array Stacking:
 - Stack two 1D arrays [1, 2, 3] and [4, 5, 6] vertically and horizontally.

In [55]:
oneArr = [1,2,3]
twoArr = [4,5,6]
horArr = np.hstack((oneArr, twoArr))
verArr = np.vstack((oneArr, twoArr))
print(f"Horizontal Stakc is {horArr}")
print(f"Verical Stack is {verArr}")

Horizontal Stakc is [1 2 3 4 5 6]
Verical Stack is [[1 2 3]
 [4 5 6]]


## Mathematical Operations:
- Perform element-wise addition and subtraction on two arrays: arr1 = np.array([2, 4,
6]) and arr2 = np.array([1, 3, 5]).
- Perform element-wise multiplication and division on two arrays: arr1 = np.array([2, 
4, 6]) and arr2 = np.array([1, 2, 3]).

In [ ]:
arr1 = np.array([2,4,6])
arr2 = np.array([1,3,5])
addResult = np.add(arr1, arr2)
print(f"The result of addition is {addResult}")
print(f"The result of division is {np.divide(arr1, arr2)}")
print(f"The result of multiplication is {np.multiply(arr1, arr2)}")

The result of addition is [ 3  7 11]
The result of division is [2.         1.33333333 1.2       ]
The result of multiplication is [ 2 12 30]


## Linear Algebra:
- Calculate the dot product of two 1D arrays: arr1 = np.array([1, 2]) and arr2 = 
np.array([3, 4]).
- Multiply two matrices using np.dot(). Given matrices A = np.array([[1, 2], [3,
4]]) and B = np.array([[5, 6], [7, 8]]), compute their dot product.


In [58]:
arr4 = np.array([1, 2]) 
arr5 = np.array([3, 4])
print(f"The dot product of two array is : {np.dot(arr1, arr2)}")

The dot product of two array is : 44
