In [2]:
import numpy as np
import pandas as pd

## Creating NumPy Arrays:
* Create a 1D NumPy array with 10 elements, containing the numbers from 1 to 10.
* Create a 2D NumPy array of shape (3, 4) filled with ones.
* Create a 3x3 identity matrix using NumPy.

In [ ]:
a1D = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
a1Dcf = np.arange(1,11) #cf = using creation function

In [8]:
print(a1D)
print(a1Dcf)

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
a2D = np.array([[1, 1, 1, 1], [1,1,1,1], [1,1,1,1]])
a2Dcf = np.ones((3,4), dtype=int)

In [44]:
print(a2D)
print(a2Dcf)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [ ]:
identityMatrix = np.array([[1,0,0],[0,1,0],[0,0,1]])
iMCf = np.eye(3, dtype=int)
iMCfD = np.diag([1,1,1]) 
print(identityMatrix)
print(iMCf)
print(iMCfD)


[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


## Array Operations:
* Add 5 to each element in a 1D NumPy array: [1, 2, 3, 4, 5].
* Multiply each element in a 1D NumPy array: [2, 4, 6, 8, 10] by 2.
* Subtract 3 from each element in a NumPy array: [6, 8, 10, 12, 14].

In [16]:
arr1 = np.arange(1,6)
result = np.add(arr1, 5)
print(arr1)
print("Rsult when 5 is added : ")
print(result)

[1 2 3 4 5]
Rsult when 5 is added : 
[ 6  7  8  9 10]


In [20]:
arr2 = np.arange(2,12,2)
print(arr2)
result2 = np.multiply(arr2, 2)
print("Result when multiplied by 2")
print(result2)

[ 2  4  6  8 10]
Result when multiplied by 2
[ 4  8 12 16 20]


In [22]:
arr3 = np.arange(6,16,2)
print(arr3)
result2 = np.subtract(arr3, 3)
print("Result when subtracted by 3")
print(result2)

[ 6  8 10 12 14]
Result when subtracted by 3
[ 3  5  7  9 11]


### Indexing and Slicing:
- Given a 1D array arr = np.array([10, 20, 30, 40, 50]), access the third 
element.
- Slice a 1D array to get the first 3 elements.
- Given a 2D array, extract the element from the second row and third column.

In [36]:
npArr = np.arange(10, 60, 10)
print(npArr)
print(f"The third elemet is {npArr[2]}")
print(f"The first theree elements are {npArr[:3]}")
np2Arr = np.array([
    [11, 12, 13],
    [21, 22, 23],
    [31, 32, 33]
])
print(np2Arr)
print(f"The element from 2nd row and 3rd column is {np2Arr[1, 2]}")

[10 20 30 40 50]
The third elemet is 30
The first theree elements are [10 20 30]
[[11 12 13]
 [21 22 23]
 [31 32 33]]
The element from 2nd row and 3rd column is 23
